name: labeling_tool
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - attrs=19.3.0=py_0
  - beautifulsoup4=4.8.2=py37_0
  - ca-certificates=2019.11.28=hecc5488_0
  - catalogue=1.0.0=py_0
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37h8022711_0
  - chardet=3.0.4=py37_1003
  - cryptography=2.8=py37h72c5cf5_1
  - cymem=2.0.3=py37he1b5a44_0
  - cython-blis=0.4.1=py37h516909a_0
  - idna=2.9=py_1
  - importlib_metadata=1.5.0=py37_0
  - jsonschema=3.2.0=py37_0
  - ld_impl_linux-64=2.33.1=h53a641e_8
  - libblas=3.8.0=15_openblas
  - libcblas=3.8.0=15_openblas
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_5
  - liblapack=3.8.0=15_openblas
  - libopenblas=0.3.8=h5ec1e0e_0
  - libprotobuf=3.11.4=h8b12597_0
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - llvm-openmp=9.0.1=hc9558a2_2
  - murmurhash=1.0.0=py37he1b5a44_0
  - mysql-connector-c=6.1.11=hc9bbbdd_1005
  - mysql-connector-python=8.0.18=py37hfcd16c1_2
  - ncurses=6.1=hf484d3e_1002
  - numpy=1.18.1=py37h95a1406_0
  - openssl=1.1.1d=h516909a_0
  - pip=20.0.2=py_2
  - plac=0.9.6=py37_0
  - preshed=3.0.2=py37he1b5a44_1
  - protobuf=3.11.4=py37he1b5a44_0
  - pycparser=2.19=py_2
  - pydub=0.23.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyrsistent=0.15.7=py37h516909a_0
  - pysocks=1.7.1=py37_0
  - python=3.7.6=h357f687_2
  - readline=8.0=hf8c457e_0
  - requests=2.23.0=py37_0
  - setuptools=45.2.0=py37_0
  - six=1.14.0=py37_0
  - soupsieve=1.9.4=py37_0
  - spacy=2.2.3=py37hc9558a2_0
  - sqlite=3.30.1=hcee41ef_0
  - srsly=1.0.0=py37he1b5a44_0
  - thinc=7.3.0=py37hc9558a2_0
  - tk=8.6.10=hed695b0_0
  - tqdm=4.43.0=py_0
  - urllib3=1.25.7=py37_0
  - wasabi=0.6.0=py_0
  - wheel=0.34.2=py_1
  - xz=5.2.4=h14c3975_1001
  - zipp=3.0.0=py_0
  - zlib=1.2.11=h516909a_1006
  - pip:
    - de-core-news-sm==2.2.5
prefix: /home/cintoros/miniconda3/envs/labeling_tool

